### ISSUE TITLE
"Keep transforms" has no effect.

### ISSUE THREAD

**Issue by nimbling** [schwa23/FigmaReplaceLayers#1]
I'm trying to replace layer, but the size of the target always changes to the source layer's size. Is this as designed?
Included: screencast of this happening:
[Screen Recording 2020-09-29 at 14.47.59-No-Audio.mp4.zip](https://github.com/schwa23/FigmaReplaceLayers/files/5299074/Screen.Recording.2020-09-29.at.14.47.59-No-Audio.mp4.zip)

**Comment by nimbling** [comment]
Hm. So, I just read note #5 in how to use (sorry), but I honestly rarely use the "K to scale" operation, I usually just set element sizes.

I'd love for this to work with sized (not scaled) instances, too.

**Comment by schwa23** [comment]
@nimbling thanks for the feedback! I've been wanting this as well -- I'll try to add this soon!

**Comment by nimbling** [comment]
Awesome :)
